// <auto-generated />
using System;
using CityPass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CityPass.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510112858_2NormalizeTo3NF")]
    partial class _2NormalizeTo3NF
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CityPass.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CityPass.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("CityPass.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassengerId"));

                    b.Property<string>("CardUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.HasKey("PassengerId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("CityPass.Models.PassengerCategory", b =>
                {
                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("PassengerId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PassengerCategories");
                });

            modelBuilder.Entity("CityPass.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TransportId")
                        .HasColumnType("integer");

                    b.HasKey("RouteId");

                    b.HasIndex("TransportId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("CityPass.Models.SystemSetting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettingID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyCap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubsequentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TransferPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("TransferTimeLimit")
                        .HasColumnType("integer");

                    b.HasKey("SettingID");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("CityPass.Models.Transport", b =>
                {
                    b.Property<int>("TransportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransportID"));

                    b.Property<string>("BoardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransportID");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("CityPass.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAnonymousTrip")
                        .HasColumnType("boolean");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StandardPriceAtMoment")
                        .HasColumnType("numeric");

                    b.Property<int>("TransportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TripDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TripId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("RouteId");

                    b.HasIndex("TransportId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("CityPass.Models.TripDiscount", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.HasKey("TripId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("TripDiscounts");
                });

            modelBuilder.Entity("CityPass.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastTransactionTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WalletId");

                    b.HasIndex("PassengerId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CityPass.Models.PassengerCategory", b =>
                {
                    b.HasOne("CityPass.Models.Category", "Category")
                        .WithMany("PassengerCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityPass.Models.Passenger", "Passenger")
                        .WithMany("PassengerCategories")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("CityPass.Models.Route", b =>
                {
                    b.HasOne("CityPass.Models.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("CityPass.Models.Trip", b =>
                {
                    b.HasOne("CityPass.Models.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityPass.Models.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityPass.Models.Transport", "Transport")
                        .WithMany()
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Route");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("CityPass.Models.TripDiscount", b =>
                {
                    b.HasOne("CityPass.Models.Discount", "Discount")
                        .WithMany("TripDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityPass.Models.Trip", "Trip")
                        .WithMany("TripDiscounts")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("CityPass.Models.Wallet", b =>
                {
                    b.HasOne("CityPass.Models.Passenger", "Passenger")
                        .WithOne("Wallet")
                        .HasForeignKey("CityPass.Models.Wallet", "PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("CityPass.Models.Category", b =>
                {
                    b.Navigation("PassengerCategories");
                });

            modelBuilder.Entity("CityPass.Models.Discount", b =>
                {
                    b.Navigation("TripDiscounts");
                });

            modelBuilder.Entity("CityPass.Models.Passenger", b =>
                {
                    b.Navigation("PassengerCategories");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CityPass.Models.Route", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("CityPass.Models.Trip", b =>
                {
                    b.Navigation("TripDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
